vartrix:
  vcf: /ceph/project/tendonhca/albrecht/resources/agne_poorva_vcf/genome1K.phase3.SNP_AF5e2.chr1toX.hg38.vcf
  fasta: /ceph/project/tendonhca/albrecht/004-deconvolution/resources/refdata-gex-GRCh38-2020-A/fasta/genome.fa
