samplesheet: "config/samples.tsv"

get_genome:
  ensembl_ftp: https://ftp.ensembl.org/pub/release-114/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz

get_genome_gtf:
  ensembl_ftp: https://ftp.ensembl.org/pub/release-114/gtf/homo_sapiens/Homo_sapiens.GRCh38.114.chr_patch_hapl_scaff.gtf.gz

star_index:
  sjdbOverhang: 149
  mem: 45G
  runtime: 1h

star_pe:
  mem: 45G
  runtime: 2h

paired_fastqs_to_ubam:
  mem: 12G
  runtime: 30m
