samplesheet: "config/samples.tsv"

get_genome:
  ensembl_ftp: https://ftp.ensembl.org/pub/release-114/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz

get_genome_gtf:
  ensembl_ftp: https://ftp.ensembl.org/pub/release-114/gtf/homo_sapiens/Homo_sapiens.GRCh38.114.chr_patch_hapl_scaff.gtf.gz

get_dbsnp_vcf:
  ncbi_ftp: https://ftp.ncbi.nih.gov/snp/archive/b157/VCF/GCF_000001405.40.gz

star_index:
  sjdbOverhang: 149
  mem: 45G
  runtime: 1h

star_pe:
  mem: 45G
  runtime: 2h

create_sequence_dictionary:
  mem: 12G
  runtime: 30m

paired_fastqs_to_ubam:
  mem: 12G
  runtime: 30m

merge_bam_alignment:
  mem: 12G
  runtime: 30m

mark_duplicates_spark:
  mem: 12G
  runtime: 6h

samtools_faidx:
  mem: 12G
  runtime: 2h

splitncigarreads:
  mem: 12G
  runtime: 4h

bcftools_mpileup:
  mem: 12G
  runtime: 1h

bcftools_call:
  mem: 12G
  runtime: 1h

gatk_baserecalibratorspark:
  mem: 4G
  runtime: 6h
