samplesheet: "config/samples.tsv"

ref_vcf_sheet: "config/common_variants.tsv"

poolsheet: "config/pools.tsv"

# get_genome:
#   ensembl_ftp: https://ftp.ensembl.org/pub/release-114/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz

# get_genome_gtf:
#   ensembl_ftp: https://ftp.ensembl.org/pub/release-114/gtf/homo_sapiens/Homo_sapiens.GRCh38.114.chr_patch_hapl_scaff.gtf.gz

get_dbsnp_vcf:
  ncbi_ftp: https://ftp.ncbi.nih.gov/snp/archive/b157/VCF/GCF_000001405.40.gz

genome_fasta: /project/tendonhca/shared/spatial/analysis/refdata-gex-GRCh38-2020-A/fasta/genome.fa

genome_gtf: /project/tendonhca/shared/spatial/analysis/refdata-gex-GRCh38-2020-A/genes/genes.gtf

# star_index: /project/tendonhca/shared/spatial/analysis/refdata-gex-GRCh38-2020-A/star/

star_index:
  sjdbOverhang: 149
  mem: 45G
  runtime: 1h

star_pe:
  mem: 45G
  runtime: 3h

create_sequence_dictionary:
  mem: 12G
  runtime: 30m

paired_fastqs_to_ubam:
  mem: 12G
  runtime: 30m

merge_bam_alignment:
  mem: 12G
  runtime: 2h

# mark_duplicates_spark:
#   mem: 12G
#   runtime: 6h

samtools_faidx:
  mem: 12G
  runtime: 2h

splitncigarreads:
  mem: 12G
  runtime: 4h

bcftools_mpileup:
  mem: 12G
  runtime: 1h

bcftools_call:
  mem: 12G
  runtime: 1h

bcftools_view:
  mem: 12G
  runtime: 10m

bcftools_merge:
  mem: 12G
  runtime: 1h

sort_vcf_same_as_bam:
  mem: 12G
  runtime: 1h

gatk_baserecalibratorspark:
  mem: 4G
  runtime: 6h

popscle_dsc:
  mem: 12G
  runtime: 6h

popscle_demuxlet:
  mem: 48G
  runtime: 6h
