from snakemake.utils import min_version


min_version("6.15.5")


configfile: "config/config.yaml"

##### Rules settings #####

#localrules:
#    na

##### load rules #####

include: "rules/common.smk"
include: "rules/cellranger.smk"

##### target rules #####

rule all:
    input:
        get_final_output(),
