from snakemake.utils import min_version


min_version("6.10.0")


configfile: "config/config.yaml"


##### load rules #####

include: "rules/common.smk"
include: "rules/spaceranger.smk"

##### target rules #####

rule all:
    input:
        get_final_output(),
