from snakemake.utils import min_version


min_version("6.10.0")


configfile: "config/config.yaml"

##### Rules settings #####

localrules:
    spaceranger_runtime,
    spaceranger_total_counts,
    gene_table,
    genes_mitochondrial,
    genes_ribosomal,
    qc_initial,
    qc_filtered_genes,
    most_abundant_feature_detection_rate,
    most_detected_most_abundant_features,
    spatial_basic_qc,
    spatial_most_detected

##### load rules #####

include: "rules/common.smk"
include: "rules/spaceranger.smk"
include: "rules/qc.smk"
include: "rules/imagemagick.smk"
include: "rules/genes.smk"

##### target rules #####

rule all:
    input:
        get_final_output(),
