from snakemake.utils import min_version


min_version("6.10.0")


configfile: "config/config.yaml"

##### Rules settings #####

localrules:
    spaceranger_runtime,
    spaceranger_total_counts

##### load rules #####

include: "rules/common.smk"
include: "rules/spaceranger.smk"
include: "rules/jupyter.smk"

##### target rules #####

rule all:
    input:
        get_final_output(),
