from snakemake.utils import min_version


min_version("6.10.0")


configfile: "config/config.yaml"


# declare https://github.com/snakemake-workflows/cellranger-multi as a module
module cellranger_multi:
    snakefile: 
        github("snakemake-workflows/cellranger-multi", path="workflow/Snakefile", branch="fix/account-for-different-output-file-paths-with-cellranger-10-0-0")
    config:
        config


# use all rules from https://github.com/snakemake-workflows/cellranger-multi
use rule * from cellranger_multi
