$schema: "http://json-schema.org/draft-07/schema#"
description: entries for the sample sheet
properties:
  sample:
    type: string
    description: sample name/identifier
  read1:
    type: string
    description: names of fastq.gz files, read 1
  read2:
    type: string
    description: names of fastq.gz files, read 2

required:
  - sample
  - read1
  - read2
